# Generated by Django 5.2.11 on 2026-02-03 17:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('legal_name', models.CharField(help_text='Full legal name as required by Art. 26 of the statutes', max_length=255, verbose_name='legal name')),
                ('country_of_residence', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='country of residence')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'historical profile',
                'verbose_name_plural': 'historical profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(help_text='Full legal name as required by Art. 26 of the statutes', max_length=255, verbose_name='legal name')),
                ('country_of_residence', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='country of residence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRoleAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('role', models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('ASOCIADO', 'Asociado'), ('BOARD_MEMBER', 'Board Member')], max_length=20, verbose_name='role')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(help_text='Typically start_date + 2 years', verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False when expired or revoked', verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'historical role assignment',
                'verbose_name_plural': 'historical role assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('ASOCIADO', 'Asociado'), ('BOARD_MEMBER', 'Board Member')], max_length=20, verbose_name='role')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(help_text='Typically start_date + 2 years', verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False when expired or revoked', verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='members.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'role assignment',
                'verbose_name_plural': 'role assignments',
                'ordering': ['-start_date'],
            },
        ),
    ]
