# Generated by Django 5.2.11 on 2026-02-03 21:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_team_historicalteam_historicalteammembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Description of what this tag represents', verbose_name='description')),
                ('category', models.CharField(choices=[('EVENT', 'Event'), ('SKILL', 'Skill'), ('RECOGNITION', 'Recognition'), ('INTEREST', 'Interest')], default='RECOGNITION', max_length=20, verbose_name='category')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for display (e.g., #FF5733)', max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class (e.g., bi-star-fill)', max_length=50, verbose_name='icon')),
                ('is_self_assignable', models.BooleanField(default=False, help_text='Can members add/remove this tag themselves?', verbose_name='self-assignable')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'community tag',
                'verbose_name_plural': 'community tags',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCommunityTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Description of what this tag represents', verbose_name='description')),
                ('category', models.CharField(choices=[('EVENT', 'Event'), ('SKILL', 'Skill'), ('RECOGNITION', 'Recognition'), ('INTEREST', 'Interest')], default='RECOGNITION', max_length=20, verbose_name='category')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for display (e.g., #FF5733)', max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class (e.g., bi-star-fill)', max_length=50, verbose_name='icon')),
                ('is_self_assignable', models.BooleanField(default=False, help_text='Can members add/remove this tag themselves?', verbose_name='self-assignable')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='display order')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical community tag',
                'verbose_name_plural': 'historical community tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProfileTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(blank=True, editable=False, verbose_name='assigned at')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why this tag was assigned', verbose_name='notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Null if self-assigned', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.profile', verbose_name='profile')),
                ('tag', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.communitytag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'historical profile tag',
                'verbose_name_plural': 'historical profile tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why this tag was assigned', verbose_name='notes')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Null if self-assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_assigned', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tags', to='members.profile', verbose_name='profile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tags', to='members.communitytag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'profile tag',
                'verbose_name_plural': 'profile tags',
                'ordering': ['tag__display_order', 'tag__name'],
                'unique_together': {('profile', 'tag')},
            },
        ),
    ]
