# Generated by Django 5.2.11 on 2026-02-03 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-friendly identifier (e.g., "privacy-policy")', unique=True, verbose_name='slug')),
                ('title', models.CharField(help_text='Display name of the document', max_length=255, verbose_name='title')),
                ('document_type', models.CharField(choices=[('PRIVACY_POLICY', 'Privacy Policy'), ('GDPR_DATA_PROCESSING', 'GDPR Data Processing Agreement'), ('CONFIDENTIALITY', 'Confidentiality Commitment'), ('CODE_OF_CONDUCT', 'Code of Conduct'), ('INTERNAL_REGULATIONS', 'Internal Regulations'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='document type')),
                ('description', models.TextField(blank=True, help_text='Brief description of what this document covers', verbose_name='description')),
                ('is_required_for_activation', models.BooleanField(default=True, help_text='Must be signed before membership becomes ACTIVE', verbose_name='required for activation')),
                ('required_for_roles', models.JSONField(blank=True, default=list, help_text='List of roles that must sign this document (empty = all roles)', verbose_name='required for roles')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which documents are displayed', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document is currently in use', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'legal document',
                'verbose_name_plural': 'legal documents',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented_at', models.DateTimeField(auto_now_add=True, verbose_name='consented at')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(verbose_name='user agent')),
                ('consent_text_shown', models.TextField(help_text='The exact text of the "I agree" statement that was displayed', verbose_name='consent text shown')),
                ('language_viewed', models.CharField(help_text='Which language version the user viewed', max_length=5, verbose_name='language viewed')),
                ('is_active', models.BooleanField(default=True, help_text='False if superseded by new version consent or revoked', verbose_name='active')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='members.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'consent record',
                'verbose_name_plural': 'consent records',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revoked_at', models.DateTimeField(auto_now_add=True, verbose_name='revoked at')),
                ('reason', models.TextField(help_text='Reason for revocation', verbose_name='reason')),
                ('consent_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revocation', to='documents.consentrecord', verbose_name='consent record')),
                ('revoked_by', models.ForeignKey(help_text='User who revoked (self or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_revocations', to=settings.AUTH_USER_MODEL, verbose_name='revoked by')),
            ],
            options={
                'verbose_name': 'consent revocation',
                'verbose_name_plural': 'consent revocations',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='Semantic version (e.g., "1.0", "2.1")', max_length=20, verbose_name='version number')),
                ('effective_date', models.DateField(help_text='Date this version becomes effective', verbose_name='effective date')),
                ('spanish_content', models.TextField(help_text='The legally binding Spanish text (Markdown or HTML)', verbose_name='Spanish content')),
                ('content_hash', models.CharField(help_text='SHA-256 hash of spanish_content for integrity verification', max_length=64, verbose_name='content hash')),
                ('git_commit_sha', models.CharField(blank=True, help_text='Git commit from which this version was synced', max_length=40, verbose_name='git commit SHA')),
                ('git_file_path', models.CharField(blank=True, help_text='Path to the file in the legal repo', max_length=255, verbose_name='git file path')),
                ('synced_at', models.DateTimeField(blank=True, help_text='When this version was last synced from git', null=True, verbose_name='synced at')),
                ('requires_re_consent', models.BooleanField(default=False, help_text='If True, existing consents to previous versions are invalidated', verbose_name='requires re-consent')),
                ('re_consent_deadline', models.DateField(blank=True, help_text='Deadline for members to re-consent to this version', null=True, verbose_name='re-consent deadline')),
                ('changelog', models.TextField(blank=True, help_text='Summary of changes from the previous version', verbose_name='changelog')),
                ('is_current', models.BooleanField(default=False, help_text='Only one version per document should be current', verbose_name='is current version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_versions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.legaldocument', verbose_name='document')),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'ordering': ['-effective_date', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='documents.documentversion', verbose_name='document version'),
        ),
        migrations.CreateModel(
            name='DocumentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('pt', 'Portuguese')], max_length=5, verbose_name='language code')),
                ('content', models.TextField(help_text='Reference translation (non-binding)', verbose_name='translated content')),
                ('is_machine_translated', models.BooleanField(default=True, help_text='Whether this was machine-translated', verbose_name='machine translated')),
                ('translator_notes', models.TextField(blank=True, verbose_name='translator notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='documents.documentversion', verbose_name='document version')),
            ],
            options={
                'verbose_name': 'document translation',
                'verbose_name_plural': 'document translations',
                'unique_together': {('document_version', 'language_code')},
            },
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['profile', 'is_active'], name='documents_c_profile_d71481_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['document_version', 'is_active'], name='documents_c_documen_43378b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
