# Generated by Django 5.2.11 on 2026-02-03 17:38

import django.db.models.deletion
import django_fsm
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='e.g., "January 2026 Review"', max_length=255, verbose_name='name')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'application batch',
                'verbose_name_plural': 'application batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(help_text='Your full legal name', max_length=255, verbose_name='legal name')),
                ('preferred_name', models.CharField(blank=True, help_text='Name you prefer to be called (optional)', max_length=255, verbose_name='preferred name')),
                ('country_of_residence', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='country of residence')),
                ('preferred_language', models.CharField(default='en', help_text='Language for communications', max_length=5, verbose_name='preferred language')),
                ('role_requested', models.CharField(choices=[('COLABORADOR', 'Colaborador (volunteer)'), ('ASOCIADO', 'Asociado (full member)')], default='COLABORADOR', max_length=20, verbose_name='role requested')),
                ('how_heard', models.TextField(blank=True, verbose_name='how did you hear about us')),
                ('motivation', models.TextField(help_text='Why do you want to join Nobodies Collective?', verbose_name='motivation')),
                ('attended_before', models.BooleanField(default=False, verbose_name='attended event before')),
                ('attended_years', models.CharField(blank=True, help_text='e.g., "2019, 2022, 2023"', max_length=255, verbose_name='years attended')),
                ('skills', models.TextField(blank=True, help_text='Skills or experience you can contribute', verbose_name='skills')),
                ('status', django_fsm.FSMField(default='SUBMITTED', max_length=50, verbose_name='status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_notes', models.TextField(blank=True, verbose_name='review notes')),
                ('data_processing_consent', models.BooleanField(default=False, help_text='Consent to process personal data for this application', verbose_name='data processing consent')),
                ('data_processing_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='consent timestamp')),
                ('data_processing_consent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='consent IP address')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.applicationbatch', verbose_name='review batch')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalApplication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('legal_name', models.CharField(help_text='Your full legal name', max_length=255, verbose_name='legal name')),
                ('preferred_name', models.CharField(blank=True, help_text='Name you prefer to be called (optional)', max_length=255, verbose_name='preferred name')),
                ('country_of_residence', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='country of residence')),
                ('preferred_language', models.CharField(default='en', help_text='Language for communications', max_length=5, verbose_name='preferred language')),
                ('role_requested', models.CharField(choices=[('COLABORADOR', 'Colaborador (volunteer)'), ('ASOCIADO', 'Asociado (full member)')], default='COLABORADOR', max_length=20, verbose_name='role requested')),
                ('how_heard', models.TextField(blank=True, verbose_name='how did you hear about us')),
                ('motivation', models.TextField(help_text='Why do you want to join Nobodies Collective?', verbose_name='motivation')),
                ('attended_before', models.BooleanField(default=False, verbose_name='attended event before')),
                ('attended_years', models.CharField(blank=True, help_text='e.g., "2019, 2022, 2023"', max_length=255, verbose_name='years attended')),
                ('skills', models.TextField(blank=True, help_text='Skills or experience you can contribute', verbose_name='skills')),
                ('status', django_fsm.FSMField(default='SUBMITTED', max_length=50, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_notes', models.TextField(blank=True, verbose_name='review notes')),
                ('data_processing_consent', models.BooleanField(default=False, help_text='Consent to process personal data for this application', verbose_name='data processing consent')),
                ('data_processing_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='consent timestamp')),
                ('data_processing_consent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='consent IP address')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.applicationbatch', verbose_name='review batch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'historical application',
                'verbose_name_plural': 'historical applications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
