# Generated by Django 5.2.11 on 2026-02-03 21:43

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('members', '0003_add_community_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='status')),
                ('export_file', models.FileField(blank=True, null=True, upload_to='gdpr_exports/%Y/%m/', verbose_name='export file')),
                ('export_file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True, verbose_name='file size')),
                ('export_checksum', models.CharField(blank=True, help_text='SHA-256 hash of the export file', max_length=64, verbose_name='checksum')),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='download token')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='download count')),
                ('first_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='first downloaded')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='celery task ID')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_requests', to='members.profile', verbose_name='profile')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'data access request',
                'verbose_name_plural': 'data access requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_snapshot', models.JSONField(blank=True, default=dict, help_text='JSON backup of profile data before deletion', verbose_name='profile snapshot')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING_CONFIRMATION', 'Pending Confirmation'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('EXECUTING', 'Executing'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='REQUESTED', max_length=25, verbose_name='status')),
                ('request_reason', models.TextField(blank=True, help_text='Why the user wants their data deleted', verbose_name='reason')),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='confirmation token')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_notes', models.TextField(blank=True, verbose_name='review notes')),
                ('denial_reason', models.TextField(blank=True, verbose_name='denial reason')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='executed at')),
                ('anonymization_log', models.JSONField(blank=True, default=dict, help_text='JSON log of what was anonymized', verbose_name='anonymization log')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='celery task ID')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_deletion_requests', to='members.profile', verbose_name='profile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
            ],
            options={
                'verbose_name': 'data deletion request',
                'verbose_name_plural': 'data deletion requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataAccessRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='status')),
                ('export_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='export file')),
                ('export_file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True, verbose_name='file size')),
                ('export_checksum', models.CharField(blank=True, help_text='SHA-256 hash of the export file', max_length=64, verbose_name='checksum')),
                ('download_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='download token')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='download count')),
                ('first_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='first downloaded')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='celery task ID')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.profile', verbose_name='profile')),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'historical data access request',
                'verbose_name_plural': 'historical data access requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDataDeletionRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('profile_snapshot', models.JSONField(blank=True, default=dict, help_text='JSON backup of profile data before deletion', verbose_name='profile snapshot')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING_CONFIRMATION', 'Pending Confirmation'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('EXECUTING', 'Executing'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='REQUESTED', max_length=25, verbose_name='status')),
                ('request_reason', models.TextField(blank=True, help_text='Why the user wants their data deleted', verbose_name='reason')),
                ('confirmation_token', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='confirmation token')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_notes', models.TextField(blank=True, verbose_name='review notes')),
                ('denial_reason', models.TextField(blank=True, verbose_name='denial reason')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='executed at')),
                ('anonymization_log', models.JSONField(blank=True, default=dict, help_text='JSON log of what was anonymized', verbose_name='anonymization log')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='celery task ID')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.profile', verbose_name='profile')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
            ],
            options={
                'verbose_name': 'historical data deletion request',
                'verbose_name_plural': 'historical data deletion requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('DATA_ACCESS', 'Data Access'), ('DATA_EXPORT', 'Data Export'), ('DATA_DELETION', 'Data Deletion'), ('CONSENT', 'Consent'), ('PROFILE', 'Profile'), ('APPLICATION', 'Application'), ('ROLE', 'Role'), ('TEAM', 'Team'), ('GOOGLE_ACCESS', 'Google Access'), ('ADMIN', 'Admin'), ('OTHER', 'Other')], db_index=True, max_length=20, verbose_name='category')),
                ('action', models.CharField(help_text='Short action identifier (e.g., "login", "export_requested")', max_length=100, verbose_name='action')),
                ('description', models.TextField(help_text='Human-readable description of what happened', verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action', verbose_name='extra data')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type')),
                ('profile', models.ForeignKey(blank=True, help_text='Profile affected by the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='members.profile', verbose_name='profile')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='gdpr_auditl_user_id_7e0c80_idx'), models.Index(fields=['profile', 'timestamp'], name='gdpr_auditl_profile_610e45_idx'), models.Index(fields=['category', 'timestamp'], name='gdpr_auditl_categor_d4cb18_idx'), models.Index(fields=['action', 'timestamp'], name='gdpr_auditl_action_28db21_idx')],
            },
        ),
    ]
