# Generated by Django 5.2.11 on 2026-02-03 18:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_team_historicalteam_historicalteammembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this resource', max_length=255, verbose_name='name')),
                ('resource_type', models.CharField(choices=[('SHARED_DRIVE', 'Shared Drive'), ('FOLDER', 'Folder'), ('FILE', 'File')], max_length=20, verbose_name='resource type')),
                ('google_id', models.CharField(help_text='Google Drive ID (from the URL or API)', max_length=255, unique=True, verbose_name='Google ID')),
                ('description', models.TextField(blank=True, help_text='What this resource is used for', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive resources are not included in provisioning', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Google resource',
                'verbose_name_plural': 'Google resources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GooglePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.CharField(help_text='Permission ID returned by Google API', max_length=255, verbose_name='Google permission ID')),
                ('permission_role', models.CharField(choices=[('reader', 'Reader'), ('commenter', 'Commenter'), ('writer', 'Writer'), ('organizer', 'Organizer'), ('fileOrganizer', 'File Organizer')], max_length=20, verbose_name='permission role')),
                ('granted_via', models.CharField(choices=[('ROLE', 'Role-based'), ('TEAM', 'Team-based'), ('MANUAL', 'Manual')], default='ROLE', max_length=20, verbose_name='granted via')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='granted at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_permissions', to='members.profile', verbose_name='profile')),
                ('team', models.ForeignKey(blank=True, help_text='If granted via team, which team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to='members.team', verbose_name='team')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='google_access.googleresource', verbose_name='resource')),
            ],
            options={
                'verbose_name': 'Google permission',
                'verbose_name_plural': 'Google permissions',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalGoogleResource',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this resource', max_length=255, verbose_name='name')),
                ('resource_type', models.CharField(choices=[('SHARED_DRIVE', 'Shared Drive'), ('FOLDER', 'Folder'), ('FILE', 'File')], max_length=20, verbose_name='resource type')),
                ('google_id', models.CharField(db_index=True, help_text='Google Drive ID (from the URL or API)', max_length=255, verbose_name='Google ID')),
                ('description', models.TextField(blank=True, help_text='What this resource is used for', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive resources are not included in provisioning', verbose_name='active')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Google resource',
                'verbose_name_plural': 'historical Google resources',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRoleGoogleAccess',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('role', models.CharField(help_text='Membership role that grants this access', max_length=20, verbose_name='role')),
                ('permission_role', models.CharField(choices=[('reader', 'Reader'), ('commenter', 'Commenter'), ('writer', 'Writer'), ('organizer', 'Organizer'), ('fileOrganizer', 'File Organizer')], default='reader', max_length=20, verbose_name='permission role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='google_access.googleresource', verbose_name='resource')),
            ],
            options={
                'verbose_name': 'historical role Google access',
                'verbose_name_plural': 'historical role Google access rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTeamGoogleAccess',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('permission_role', models.CharField(choices=[('reader', 'Reader'), ('commenter', 'Commenter'), ('writer', 'Writer'), ('organizer', 'Organizer'), ('fileOrganizer', 'File Organizer')], default='reader', max_length=20, verbose_name='permission role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='google_access.googleresource', verbose_name='resource')),
                ('team', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'historical team Google access',
                'verbose_name_plural': 'historical team Google access rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GooglePermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('GRANT', 'Grant'), ('REVOKE', 'Revoke'), ('RECONCILE_GRANT', 'Reconcile Grant'), ('RECONCILE_REVOKE', 'Reconcile Revoke')], max_length=20, verbose_name='operation')),
                ('permission_role', models.CharField(blank=True, choices=[('reader', 'Reader'), ('commenter', 'Commenter'), ('writer', 'Writer'), ('organizer', 'Organizer'), ('fileOrganizer', 'File Organizer')], max_length=20, null=True, verbose_name='permission role')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20, verbose_name='status')),
                ('permission_id', models.CharField(blank=True, help_text='Permission ID if operation succeeded', max_length=255, verbose_name='permission ID')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='retry count')),
                ('triggered_by', models.CharField(blank=True, help_text='What triggered this operation (e.g., "status_change", "reconciliation")', max_length=50, verbose_name='triggered by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_permission_logs', to='members.profile', verbose_name='profile')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_logs', to='google_access.googleresource', verbose_name='resource')),
            ],
            options={
                'verbose_name': 'Google permission log',
                'verbose_name_plural': 'Google permission logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='google_acce_profile_a9894a_idx'), models.Index(fields=['status', 'created_at'], name='google_acce_status_7e08a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleGoogleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Membership role that grants this access', max_length=20, verbose_name='role')),
                ('permission_role', models.CharField(choices=[('reader', 'Reader'), ('commenter', 'Commenter'), ('writer', 'Writer'), ('organizer', 'Organizer'), ('fileOrganizer', 'File Organizer')], default='reader', max_length=20, verbose_name='permission role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_access_rules', to='google_access.googleresource', verbose_name='resource')),
            ],
            options={
                'verbose_name': 'role Google access',
                'verbose_name_plural': 'role Google access rules',
                'unique_together': {('role', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='TeamGoogleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_role', models.CharField(choices=[('reader', 'Reader'), ('commenter', 'Commenter'), ('writer', 'Writer'), ('organizer', 'Organizer'), ('fileOrganizer', 'File Organizer')], default='reader', max_length=20, verbose_name='permission role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_access_rules', to='google_access.googleresource', verbose_name='resource')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_access_rules', to='members.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'team Google access',
                'verbose_name_plural': 'team Google access rules',
                'unique_together': {('team', 'resource')},
            },
        ),
    ]
